"""Initial migration

Revision ID: ea9b8a4765e4
Revises: 
Create Date: 2025-01-25 18:48:01.114154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9b8a4765e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('artikul', sa.Integer(), nullable=False, comment='Артикул товара'),
    sa.Column('name', sa.String(), nullable=False, comment='Название товара'),
    sa.Column('price', sa.Float(), nullable=True, comment='Цена товара в рублях'),
    sa.Column('rating', sa.Float(), nullable=True, comment='Рейтинг товара'),
    sa.Column('stock', sa.Integer(), nullable=True, comment='Количество товара на складе'),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления данных'),
    sa.PrimaryKeyConstraint('artikul'),
    sa.UniqueConstraint('artikul')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
